
language: python
python: 3.8

branches:
  only:
    - main

jobs:
  include:
    - if: commit_message !~ /\[deploy\]/
      # install dependencies
      install:
        - skip

      # run all tests
      script:
        - cp -r molecular/tests/samples ./samples
        - cp molecular/tests/test.py .
      #  - python -m coverage run test.py
        - coverage run -m unittest test.py
        - rm test.py

      # after a successful test, update to codecov
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - |
          version=$(python _scripts/increment_version.py)
          cd docs
          rm -rf source/api/generated
          rm -rf build
          make html
          cd ..
          git config user.name "doclockh"
          git config user.email "chris@lockhartlab.org"
          git checkout main
          git add -A
          git commit -m "[deploy] ${TRAVIS_COMMIT_MESSAGE}"
          git push -fq https://doclockh:"${GIT_API_KEY}"@github.com/"${TRAVIS_REPO_SLUG}".git main:main

    - if: commit_message =~ /\[deploy\]/
      #
      script:
        - echo 0

      # deploy to pyp
      deploy:
        - provider: pypi
          user: "__token__"
          password:
            secure: "H1izncpSp+yWMAwKYiEZAQYWXMO1ilTFjhxb1N9i0MYWIJb7TquuelUlVDwff1B+7BeGb3wxX5gZTwjGQn8R5hJLl7pRsW7d3w1Gsz/kmowv6LTCvU39VFsyKq5GNtia4CqYSDt1GwYaaa7bxrVpW2JaQN4zH2fjSrYHkcPSKdKKFFbOjCyaqe/PTAAlP2umJdTdB74xxPj/ZoYQ3xCggQI1In4vTBMeKy6lI+PAckgGFZVoZQ3hLo2+JNxG6hLqLxym7pevWlCl4wSWNN6mFUehWzMUHOx2bxdG0/nO+udX04pQD+vOWfcKn69dgXFvCLsadaG6lGm8dffp+MEl/fkBCpVO31ADWHE0VNEplq4Ws0g+g3Ack9ITlC/GY12Fhm8SIeQOBgpr8UMqY3+0O5VU1PcTbzRQh9E4lTaozqjsnHrr+I6OlLNl7K5thgEcMbdWrEFUAynIMC988216bjQiwL9xlvCohBAqZypxTDYMvU6Lo94fFb/ffaUuiQh9Qc/Li4CdaBFS+cpCAapsPoWs4loBs3fcLeqfhGYfvQ6IKabStkb9QjM2aWZSeOgx/9FFYDsg7T9gA/XxQbjFQDoY0uEIMLmK6TrE5iPk741h12d83DBG1gLbuevnuySKzuPpTqazivSaPjij2AHnFjtYtV4ackUbpjePFAwLcsQ="
          twine_check: true
          skip_cleanup: true
          on:
            branch: main
#            tags: true

notifications:
  email:
    on_success: never
    on_failure: always
